# Generated by Django 5.2.2 on 2025-06-07 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.TextField()),
                ('nb_terrain', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_reservation', models.DateTimeField(auto_now_add=True)),
                ('date_jeu_souhaitee', models.DateField()),
                ('heure_debut_souhaitee', models.TimeField()),
                ('nb_personnes', models.PositiveSmallIntegerField(choices=[(1, '1 personne(s)'), (2, '2 personne(s)'), (3, '3 personne(s)'), (4, '4 personne(s)')])),
                ('etat_reservation', models.CharField(choices=[('E', 'En attente'), ('C', 'Confirmée')], default='E', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=100)),
                ('adresse', models.TextField()),
                ('numero_tel', models.CharField(max_length=20)),
                ('niveau', models.CharField(max_length=50)),
                ('genre', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], max_length=1)),
                ('role', models.CharField(choices=[('J', 'Joueur'), ('P', 'Propriétaire')], max_length=1)),
                ('url_image', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temps_de_jeu', models.DurationField()),
                ('score', models.CharField(blank=True, max_length=100, null=True)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservation_app.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=6)),
                ('mode_paiement', models.CharField(max_length=50)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservation_app.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='Terrain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(max_length=50)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=6)),
                ('temps', models.DurationField()),
                ('etat', models.CharField(choices=[('NR', 'Non réservé'), ('R', 'Réservé'), ('M', 'Maintenance')], default='NR', max_length=2)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terrains', to='reservation_app.centre')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='terrain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation_app.terrain'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation_app.user'),
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='default@example.com', max_length=254)),
                ('mot_de_passe', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservation_app.user')),
            ],
        ),
        migrations.AddField(
            model_name='centre',
            name='proprietaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centres', to='reservation_app.user'),
        ),
    ]
