# Generated by Django 5.2.1 on 2025-06-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='centre',
            name='gouvernorat',
            field=models.CharField(default='Tunis', max_length=100),
        ),
    ]
